name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test & Lint"
    steps:
      - name: "Setup go"
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.3'
          check-latest: true
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Checking go mod tidy"
        run: |
          set -e
          go mod tidy
          git diff --quiet && exit 0
          cat <<EOF
          Please run `go mod tidy` and update your branch.
          EOF
      - name: "Run tests"
        run:
          go test -race ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
      - name: "Linting"
        run: go vet ./...
      - name: "staticcheck"
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2022.1"
          install-go: false
      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1.1
        with:
          filename: coverage.out
